### ISSUE TITLE
problem Case

### ISSUE THREAD

**Issue by llronaldoll** [poggit-orphanage/ItemCase#6]
item disappears temporarily from the case, and only reappears again using / itemcase respawn

**Comment by Awzaw** [comment]
Have you got any plugins installed that remove entities such as clearlagg?

**Comment by llronaldoll** [comment]
no

**Comment by CupidonSauce173** [comment]
Same problem...I fixed it with a plugin that execute commands after a x amount of ticks...maybe you should too.

**Comment by Awzaw** [comment]
I can't reproduce this. Please try without TeaSpoon and any other plugins that are known to be be full of bugs.
